services:  
  nginx:
      image: alfg/nginx-rtmp
      container_name:  rtmp-server
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf.template
      ports:
        - "1935:1935"
        - "8080:8080"